Repository Tyresius92/le-chat, pull requests merged in 2020-06, with the labels that each got.

#22 implement create conversation mutation
  server/src/schema/ConversationType.js
  server/src/schema/NewConversationInputType.js
  server/src/schema/NewConversationPayloadType.js
  server/src/schema/UserType.js
  server/src/schema/__tests__/UserType.test.js
  server/src/schema/index.js
  server/src/services/conversation.js
  server/src/services/user.js
Labels: Priority: High, Status: Ready for Review, Type: Enhancement/Feature

#18 update the seed database function
  README.md
  server/init_dev_db.sh
  server/src/seedDatabase.js
Labels: Status: Ready for Review, Type: Enhancement/Feature

#21 add current user to context
  server/src/index.js
  server/src/schema/UserType.js
  server/src/schema/__tests__/UserType.test.js
  server/src/services/conversation.js
Labels: Status: Ready for Review, Type: Enhancement/Feature

#27 bump apollo server version to fix security vulnerability
  server/package-lock.json
  server/package.json
Labels: Priority: Medium, Status: Ready for Review, Type: Enhancement/Feature

#28 specify foreign key relationships
  server/init_dev_db.sh
Labels: Priority: Medium, Status: Ready for Review, Type: Enhancement/Feature

#26 add apollo client
  client/package-lock.json
  client/package.json
  client/src/apolloClient.js
  client/src/components/App.js
  client/src/index.js
Labels: Priority: Medium, Status: Ready for Review, Type: Enhancement/Feature

#30 Add .circleci/config.yml
  .circleci/config.yml
Labels: Priority: High, Status: Ready for Review, Type: Enhancement/Feature

#58 Create feature and bug issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Priority: Medium, Status: Ready for Review, Type: Enhancement/Feature

#41 add chakra and a test util
  client/src/components/__tests__/App.test.js
  client/src/testUtils/renderWrapper.js
Labels: Priority: High, Status: Ready For Merge, Type: Enhancement/Feature

#67 provide cross platform cli color support
  client/package.json
  client/scripts/echo.js
  package.json
  scripts/echo.js
  server/package.json
  server/scripts/echo.js
Labels: Priority: High, Status: Ready for Review, Type: Bug
